version: '2'
services:
  app:
    image: 'hamzagbada/crud:1.0'
    ports:
      - "9090:9090"
    environment:
      - MONGO_HOST=mongodb
    depends_on:
      - mongodb
  mongodb:
    image: 'mongo'
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: test
    volumes:
      - ~/db:/data/db
